config:
  SIAB_SSL: "true"

replicas: 1

nodeSelector: {}

tolerations: []

image: sspreitzer/shellinabox
tag: centos
imagePullPolicy: Always

ingress:
  enabled: false
  annotations:

  tls: false
  host: shell.example.com
  tlsSecret: shellinabox-tls
