apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "shellinabox.fullname" . }}
  labels:
    {{- include "shellinabox.labels" . | indent 4 }}
data:
  {{- .Values.config | toYaml | nindent 2 }}
