apiVersion: apps/v1
kind: Deployment
metadata:
  name: "{{ .Release.Name }}"
  labels:
    {{- include "shellinabox.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        {{- include "shellinabox.labels" . | indent 8 }}
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- .Values.nodeSelector | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      tolerations:
        {{- .Values.tolerations | toYaml | nindent 8 }}
      {{- end }}
      containers:
        - name: shellinabox
          image: {{ .Values.image }}:{{ .Values.tag }}
          envFrom:
            - configMapRef:
                name: {{ .Release.Name }}
          ports:
            - containerPort: 4200
