apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shellinabox.fullname" . }}
  labels:
    {{- include "shellinabox.labels" . | indent 4 }}
  annotations:
    checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yml") . | sha256sum }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ include "shellinabox.fullname" . }}
  template:
    metadata:
      labels:
        {{- include "shellinabox.labels" . | indent 8 }}
      annotations:
        checksum/configmap: {{ include (print $.Template.BasePath "/configmap.yml") . | sha256sum }}
    spec:
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{- .Values.nodeSelector | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      tolerations:
        {{- .Values.tolerations | toYaml | nindent 8 }}
      {{- end }}
      containers:
        - name: shellinabox
          image: {{ .Values.image }}:{{ .Values.tag }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "shellinabox.fullname" . }}
          ports:
            - containerPort: 4200
