{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "shellinabox.fullname" . }}
  labels:
   {{- include "shellinabox.labels" . | nindent 4 }}
  {{- if .Values.ingress.annotations }}
  annotations:
    {{- .Values.ingress.annotations | toYaml | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
    - hosts:
      - "{{ .Values.ingress.host }}"
      secretName: "{{ .Values.ingress.tlsSecret }}"
{{- end }}
  rules:
    - host: "{{ .Values.ingress.host }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "shellinabox.fullname" . }}
                port:
                  number: 4200
{{- end -}}
