apiVersion: v1
kind: Service
metadata:
  name: {{ include "shellinabox.fullname" . }}
  labels:
    {{- include "shellinabox.labels" . | indent 4 }}
spec:
  selector:
    app: {{ include "shellinabox.fullname" . }}
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200
