apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}"
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{- include "shellinabox.labels" . | indent 4 }}
spec:
  selector:
    app: "{{ .Release.Name }}"
  ports:
    - protocol: TCP
      port: 4200
      targetPort: 4200
